### ISSUE TITLE
[Question] What happens when you try to have 2 looking glass views looking at each other?

### ISSUE THREAD

**Issue by darkdurza** [XCompWiz/LookingGlass#22]
Playing with DarkholmeTenk's Tardis mod and suggested having his magic doors render what's on the other side, but he said it wasn't possible with the looking glass API:

> darkdurza commented an hour ago
> I think it would be awesome if, instead of the star background, the magic doors had an image of the room on the other side.
> 
> DarkholmeTenk commented an hour ago
> Nope, tried this, couldn't get it to come anywhere close to working. Too many chances for door a -> door b -> door a rendering causing an infinite render loop, when I tried with looking glass and I don't have the skill nor time to implement this myself.

Is there no way to have it not render any looking glass views, or only render up to X views deep?

**Comment by Guichaguri** [comment]
In theory, I don't see any problem, since currently it renders a view to texture, so it would render a texture inside a texture. I have not tested this though

**Comment by XCompWiz** [comment]
Since LookingGlass just does a render-to-texture, there should be no loops.  However, using that for portals results in some very flat looking portals.  I've been working on some proper portal renders, but I think that will get backburnered to after updating and other fixes.

To answer the question, you should see the render as it was last frame.
