### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by steampunko** [XCompWiz/LookingGlass#31]
This isn't an issue, but I'm just wondering.

**Comment by denzuko** [comment]
@steampunko To quote [XCompWiz](https://minecraft.curseforge.com/projects/lookingglass?comment=28): "I hope to update it to 1.10 when I have time."

so I'm guess it is. I'd love to help XCompWiz out on this however and since the maths and code are well done already I might be able to do a port to 1.10 and 1.12 given I'm not bogged down too much with bugs.

**Comment by XCompWiz** [comment]
See branch
