### ISSUE TITLE
LookingGlass + MapWriter Bug

### ISSUE THREAD

**Issue by shadowfacts** [XCompWiz/LookingGlass#4]
When using LookingGlass to view a dimension (either using `/lg-viewdim` or via a Mystcraft Linking Book), the dimension that MapWriter (technically it's Opis) changes the current dimension to whatever dimension is being viewed.

**Comment by XCompWiz** [comment]
As in, MapWriter displays the wrong dimension number or the wrong map? Can you provide a screenshot?

**Comment by heldplayer** [comment]
MapWriter displays the wrong dimension in its map, it assumes the player is in the dimension that was loading via LookingGlass.

This is an issue with MapWriter itself.

**Comment by XCompWiz** [comment]
That's interesting. Makes me wonder how MapWriter is pulling the world when rendering, and when it is rendering.
Sounds like it might be rendering during the actual world rendering.  I'd recommend that, as a HUD overlay, it should render using the render tick, not a in-world render.  ~~However, I think LookingGlass is currently partially rendering the vanilla HUD, and shouldn't be. Changing that might fix it.~~
I take it back, hideGUI is on when rendering the proxy worlds.  This issue is probably something MapWriter is going to have to fix.
As I understand it, JourneyMap works fine, so that's an option.

**Comment by TruePikachu** [comment]
If anyone's interested, I've located the actual issue in Opis's version of Mapwriter. [java/mapwriter/Mw.java:updatePlayer](https://bitbucket.org/ProfMobius/opis/src/d7e8ed208175fe7dc22a7686a773fe5f711fbbf9/src/main/java/mapwriter/Mw.java?at=forge_1208&fileviewer=file-view-default#Mw.java-287) refers to the [`onWorldLoad`](https://bitbucket.org/ProfMobius/opis/src/d7e8ed208175fe7dc22a7686a773fe5f711fbbf9/src/main/java/mapwriter/Mw.java?at=forge_1208&fileviewer=file-view-default#Mw.java-577) event, which is supposed to determine what dimension the player is in. However, since LookingGlass needs to do things which trigger `onWorldLoad` for other dimensions, it assumes the player had just entered the dimension associated with the world that loaded.

**Comment by XCompWiz** [comment]
That's good to know! :D
Unfortunately, I cannot do anything about that. The event MUST be called.  Hopefully the assumption of "this must be the dimension the player is in" can be broken.
